### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by andis-sprinkis** [hismailbulut/neoray#25]
**Please complete the following information:**
 - OS or distro: Windows 10 x64
 - neoray version: 0.1.1

**Describe the bug**

**Steps to reproduce**

**Your neoray config in init.vim** (Only the part that concerns neoray!)
```vim

```

**Crash log if available (may be generated by neoray after crash)**
NEORAY v0.1.1 Release Crash Report 2021-09-24 14:29:21.8315012 +0000 UTC
Please open an issue in github with this file.
The program is crashed because of the following reasons:
[FATAL] [NEORAY] [PANIC!] runtime error: invalid memory address or nil pointer dereference

goroutine dump:
goroutine 1 [running, locked to thread]:
main.createCrashReport({0xc000452060, 0x5b})
	D:/a/neoray/neoray/src/logger.go:104 +0x330
main.logMessage(0x35b7e8, 0xc0, {0xc00035b7f0, 0xc00035b7f8, 0x662000})
	D:/a/neoray/neoray/src/logger.go:168 +0x25a
main.shutdownLogger()
	D:/a/neoray/neoray/src/logger.go:77 +0x70
panic({0x66af80, 0x5d4ae0})
	C:/hostedtoolcache/windows/go/1.17.1/x64/src/runtime/panic.go:1038 +0x215
main.(*Font).GetCellSize(0xc00035ba80)
	D:/a/neoray/neoray/src/font.go:166 +0x43
main.(*Renderer).updateCellSize(0x842450, 0xc000398cd0)
	D:/a/neoray/neoray/src/renderer.go:107 +0x25
main.(*Renderer).setFont(0x842450, {0x41500000, {0xc000454330, 0x10}, 0xc000380e00, 0x0, 0x0, 0x0})
	D:/a/neoray/neoray/src/renderer.go:68 +0xab
main.(*UIOptions).setGuiFont(0x842530, {0xc000454048, 0x842450})
	D:/a/neoray/neoray/src/uioptions.go:65 +0x26a
main.option_set({0xc00045c990, 0x1, 0xffffffffffffffff})
	D:/a/neoray/neoray/src/redrawevents.go:108 +0x265
main.handleRedrawEvents()
	D:/a/neoray/neoray/src/redrawevents.go:28 +0x4b9
main.(*Editor).update(0x8422c0)
	D:/a/neoray/neoray/src/editor.go:179 +0x1e
main.(*Editor).MainLoop(0x8422c0)
	D:/a/neoray/neoray/src/editor.go:162 +0x38a
main.main()
	D:/a/neoray/neoray/src/main.go:71 +0x296

goroutine 13 [chan send]:
main.(*NvimProcess).startUI.func2()
	D:/a/neoray/neoray/src/nvimproc.go:195 +0xcc
created by main.(*NvimProcess).startUI
	D:/a/neoray/neoray/src/nvimproc.go:189 +0x3b4

**Debug output (you can generate starting neoray with --verbose option)**

**Comment by hismailbulut** [comment]
I am not sure this is the last crash issue because I always touch/broke working things :) I will release again this version because this is a very important issue. Thanks.
